# Generated by Django 4.2.27 on 2025-12-09 11:54

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('description', ckeditor.fields.RichTextField()),
                ('event_type', models.CharField(choices=[('Workshop', 'Workshop'), ('Seminar', 'Seminar'), ('Conference', 'Conference'), ('Webinar', 'Webinar'), ('Competition', 'Competition'), ('Hackathon', 'Hackathon'), ('Meeting', 'Meeting'), ('Social', 'Social Event'), ('Other', 'Other')], max_length=50)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', max_length=20)),
                ('date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(max_length=200)),
                ('venue_link', models.URLField(blank=True, help_text='Google Maps or virtual meeting link')),
                ('image', models.ImageField(blank=True, upload_to='events/')),
                ('banner', models.ImageField(blank=True, upload_to='events/banners/')),
                ('registration_link', models.URLField(blank=True)),
                ('registration_deadline', models.DateTimeField(blank=True, null=True)),
                ('max_participants', models.IntegerField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('speakers', models.TextField(blank=True, help_text='Speaker names, comma-separated')),
                ('prerequisites', ckeditor.fields.RichTextField(blank=True)),
                ('outcome', ckeditor.fields.RichTextField(blank=True, help_text='What participants will learn')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('batch', models.CharField(max_length=10)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('attended', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event')),
            ],
            options={
                'ordering': ['-registered_at'],
                'unique_together': {('event', 'email')},
            },
        ),
    ]
