# Generated by Django 4.2.27 on 2026-01-04 15:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0002_alter_member_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('achievement_type', models.CharField(choices=[('award', 'Award'), ('milestone', 'Milestone'), ('record', 'Record'), ('certification', 'Certification'), ('event', 'Event')], max_length=20)),
                ('date_achieved', models.DateField()),
                ('icon', models.CharField(default='fa-trophy', help_text='Font Awesome icon class (e.g., fa-trophy)', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='achievements/')),
                ('stat_value', models.CharField(blank=True, help_text='E.g., 500, 1000+', max_length=100)),
                ('stat_label', models.CharField(blank=True, help_text='E.g., Members, Events', max_length=100)),
                ('is_featured', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Achievement',
                'verbose_name_plural': 'Achievements',
                'ordering': ['display_order', '-date_achieved'],
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='announcements/')),
                ('background_color', models.CharField(default='#667eea', help_text='Hex color code (e.g., #667eea)', max_length=7)),
                ('button_text', models.CharField(blank=True, default='Learn More', max_length=100)),
                ('button_link', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('testimonial_text', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('rating', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('is_featured', models.BooleanField(default=False)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MemberSpotlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotlight_title', models.CharField(default='Member Spotlight', max_length=200)),
                ('spotlight_text', models.TextField(blank=True, help_text='Custom spotlight description')),
                ('key_achievement', models.CharField(blank=True, max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
            ],
            options={
                'verbose_name': 'Member Spotlight',
                'verbose_name_plural': 'Member Spotlights',
                'ordering': ['display_order', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ActivityFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('blog', 'Blog Post'), ('news', 'News Update'), ('event', 'Event'), ('member', 'Member Joined'), ('achievement', 'Achievement'), ('resource', 'Resource Added')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='fa-bell', help_text='Font Awesome icon class', max_length=50)),
                ('link_url', models.URLField(blank=True)),
                ('auto_generated', models.BooleanField(default=True)),
                ('related_content_type', models.CharField(blank=True, max_length=50)),
                ('related_object_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Activity Feed',
                'verbose_name_plural': 'Activity Feeds',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='homepage_fe_created_fc20bb_idx')],
            },
        ),
    ]
