# Generated by Django 4.2.27 on 2026-01-04 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(db_index=True, max_length=255)),
                ('count', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_searched', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Search Query',
                'verbose_name_plural': 'Search Queries',
                'ordering': ['-count', '-last_searched'],
            },
        ),
        migrations.CreateModel(
            name='UserRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('content_type', models.CharField(choices=[('blog', 'Blog Post'), ('news', 'News Update'), ('event', 'Event'), ('resource', 'Resource'), ('member', 'Member')], max_length=50)),
                ('object_id', models.IntegerField()),
                ('interaction_type', models.CharField(choices=[('view', 'View'), ('click', 'Click'), ('read', 'Read'), ('search', 'Search')], default='view', max_length=10)),
                ('score', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'User Recommendation',
                'verbose_name_plural': 'User Recommendations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session_key', '-created_at'], name='search_user_session_bc56e4_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContentView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('blog', 'Blog Post'), ('news', 'News Update'), ('event', 'Event'), ('resource', 'Resource'), ('member', 'Member'), ('gallery', 'Gallery Image')], max_length=50)),
                ('object_id', models.IntegerField()),
                ('view_count', models.IntegerField(default=0)),
                ('weekly_views', models.IntegerField(default=0)),
                ('last_viewed', models.DateTimeField(auto_now=True)),
                ('weekly_reset_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Content View',
                'verbose_name_plural': 'Content Views',
                'indexes': [models.Index(fields=['-weekly_views'], name='search_cont_weekly__9c2828_idx'), models.Index(fields=['-view_count'], name='search_cont_view_co_31bd73_idx')],
                'unique_together': {('content_type', 'object_id')},
            },
        ),
    ]
