# Generated by Django 4.2.27 on 2025-12-09 11:54

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(choices=[('President', 'President'), ('Vice President', 'Vice President'), ('Secretary', 'Secretary'), ('Treasurer', 'Treasurer'), ('Technical Lead', 'Technical Lead'), ('Research Head', 'Research Head'), ('Media Head', 'Media Head'), ('Senior Member', 'Senior Member'), ('Junior Member', 'Junior Member'), ('Core Member', 'Core Member')], max_length=50)),
                ('team', models.CharField(choices=[('Executive Committee', 'Executive Committee'), ('Advisory Board', 'Advisory Board')], default='Executive Committee', max_length=50)),
                ('role_in_project', models.CharField(max_length=100)),
                ('batch', models.CharField(choices=[('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025')], max_length=10)),
                ('bio', ckeditor.fields.RichTextField(max_length=1000)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='members/')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('linkedin', models.URLField(blank=True)),
                ('github', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('join_date', models.DateField(blank=True, null=True)),
                ('specialization', models.CharField(blank=True, max_length=200)),
                ('achievements', ckeditor.fields.RichTextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['team', 'display_order', 'name'],
            },
        ),
    ]
