# Generated by Django 4.2.27 on 2025-12-09 11:54

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='fa-file', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Resource Categories',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', ckeditor.fields.RichTextField()),
                ('resource_type', models.CharField(choices=[('document', 'Document'), ('link', 'External Link'), ('video', 'Video'), ('tool', 'Tool/Software')], max_length=20)),
                ('file', models.FileField(blank=True, upload_to='resources/files/')),
                ('external_link', models.URLField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, upload_to='resources/thumbnails/')),
                ('uploaded_by', models.CharField(max_length=100)),
                ('download_count', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('tags', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.resourcecategory')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
